# Generated by Django 5.2.4 on 2025-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'content')},
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
