# Generated by Django 5.2.4 on 2025-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_unique_together_alter_note_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
